name: Build and Deploy
on:
  push:
    branches:
      - master  # Trigger the workflow on pushing to the master branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Set up Java for Maven to build the Spring Boot backend
      - name: Set up Java 18
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'temurin'
          cache: 'maven'  # Cache Maven packages for faster builds
          
      # Build the backend using Maven
      - name: Build Backend
        run: |
          cd Backend
           chmod +x ./mvnw
          ./mvnw clean package -DskipTests  # Package without running tests for speed
      
      # Set up Node.js for React frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json
          
      # Install dependencies and build the frontend
      - name: Build Frontend
        run: |
          cd Frontend
          npm ci  # Clean install, more reliable than npm install in CI environments
          npm run build
      
      # Deploy to Railway using their recommended approach
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
      
      - name: Deploy to Railway
        run: |
          railway up --detach --service "$RAILWAY_SERVICE_NAME"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE_NAME: ${{ secrets.RAILWAY_SERVICE_NAME }}
